In [1]:
import requests


In [4]:
url = 'http://10.100.30.239:1222/generate'

In [7]:
import concurrent.futures
import requests
import time

# Define the prompt and substrings for the requests
prompt = '''There is a request from the user to create a task in task management system. Please, extract the status of this task that will be placed in Task Management System.
Example 1: "We have finished the penetration testing. Update the status of the pentest task to completed in the system."
Answer: "completed"

Example 2: "In our ongoing sprint, Vanya is responsible for code refactoring. Create a code refactoring task for Vanya and set the status to in progress."
Answer: "in progress"

Example 3: "I need to know who is assigned to the task of charting. Show me the executors of the task of charting."
Answer: "null"

Example 4: "The marketing team has requested to purchase some candy for the upcoming event. Create a task to buy candy and set the status to in progress."
Answer: "in progress"

Example 5: "The database cleanup is pending. Create a task to clean the database and mark it as not started."
Answer: "not started"

Example 6: "Our new feature is ready for testing. Set the status of the task to test the new feature to in review."
Answer: "in review"

Example 7: "The technical documentation update is completed. The task to update documentation should be marked as completed."
Answer: "completed"

Example 8: "We are starting the deployment process. Change the status of the deployment task to in progress."
Answer: "in progress"

Example 9: "We need to address several bugs reported by the QA team. Set the bug fix task status to in progress."
Answer: "in progress"

Example 10: "Organize a meeting to discuss the new project requirements. Create a task to organize the meeting and set the status to scheduled."
Answer: "scheduled"'''

substrings = [
    "The marketing team has requested to purchase some candy for the upcoming event. Create a task to buy candy and set the status to in progress. Example 1: Update the status of the pentest task to completed. Answer: “completed” Example 2: “Create a code refactoring task for Vanya. And set the status to “in progress” Answer: “in progress”. Example 3: “Show me the executors of the task of charting”. Answer: “null”.",
    "We have finished the penetration testing. Update the status of the pentest task to completed in the system.",
    "In our ongoing sprint, Vanya is responsible for code refactoring. Create a code refactoring task for Vanya and set the status to in progress.",
    "I need to know who is assigned to the task of charting. Show me the executors of the task of charting.",
    "The database cleanup is pending. Create a task to clean the database and mark it as not started.",
    "Our new feature is ready for testing. Set the status of the task to test the new feature to in review.",
    "The technical documentation update is completed. The task to update documentation should be marked as completed.",
    "We are starting the deployment process. Change the status of the deployment task to in progress.",
    "We need to address several bugs reported by the QA team. Set the bug fix task status to in progress.",
    "Organize a meeting to discuss the new project requirements. Create a task to organize the meeting and set the status to scheduled."
]


def make_request(substring):
    payload = {
        'prompt': prompt,
        'substring': substring
    }
    s = time.time()
    response = requests.post(url, json=payload)
    e = time.time()
    return response.text, e - s

# Use ThreadPoolExecutor to make 10 parallel requests
with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
    futures = [executor.submit(make_request, substring) for substring in substrings]
    for future in concurrent.futures.as_completed(futures):
        response_text, duration = future.result()
        print(f"Response: {response_text} (Time taken: {duration} seconds)")


Response: "process. Change the" (Time taken: 19.74884557723999 seconds)
Response: "should be marked" (Time taken: 20.564838886260986 seconds)
Response: "penetration testing. Update" (Time taken: 22.39855980873108 seconds)
Response: "Create a task" (Time taken: 23.212981700897217 seconds)
Response: "project requirements. Create" (Time taken: 24.913835048675537 seconds)
Response: "executors of the task" (Time taken: 26.576987743377686 seconds)
Response: "ongoing sprint, Vanya" (Time taken: 26.596738576889038 seconds)
Response: "upcoming event. Create" (Time taken: 27.220906257629395 seconds)
Response: "Set the status of" (Time taken: 27.229764938354492 seconds)
Response: "several bugs reported by" (Time taken: 27.226872444152832 seconds)


In [7]:
import time

prompt = '''There is a request from the user to create a task in task management system. Please, extract the status of this task that will be placed in Task Management System.
Example 1: Update the status of the pentest task to completed.
Answer: “completed”

Example 2: “Create a code refactoring task for Vanya. And set the status to “in progress”
Answer: “in progress”.

Example 3: “Show me the executors of the task of charting”.
Answer: “null”.

Example 4: “Create a task to buy candy, status - in progress”.
Answer: “'''

substirng = "Create a task to buy candy, status - in progress"

substring_example = {'prompt': prompt, 'substring': substirng}
s = time.time()
x = requests.post(url, json = substring_example)
e = time.time()

print(x.text)
e - s

"in progress"


0.6148166656494141

In [4]:
prompt = '''There is a request from the user to create a task in task management system. Please, extract the status of this task that will be placed in Task Management System.
Example 1: Обнови статус задачи по проведению пентеста на выполнено.
Answer: "выполнено"

Example 2: "Создай Ване задачу по рефакторингу кода. И поставь статус - в процессе"
Answer: "в процессе"

Example 3: "Покажи мне исполнителей задачи по построению графиков"
Answer: "null"

Example 4: "Создай задачу купить конфет, статус в процессе"
Answer: "'''

print(prompt)

There is a request from the user to create a task in task management system. Please, extract the status of this task that will be placed in Task Management System.
Example 1: Обнови статус задачи по проведению пентеста на выполнено.
Answer: "выполнено"

Example 2: "Создай Ване задачу по рефакторингу кода. И поставь статус - в процессе"
Answer: "в процессе"

Example 3: "Покажи мне исполнителей задачи по построению графиков"
Answer: "null"

Example 4: "Создай задачу купить конфет, статус в процессе"
Answer: "


In [5]:
# если бы is_fast=False:
# 1.2900440692901611

import time

substirng = "Создай задачу купить конфет, статус в процессе"

substring_example = {'prompt': prompt, 'substring': substirng}
s = time.time()
x = requests.post(url, json = substring_example)
e = time.time()

print(x.text)
e - s

["в процессе"]


0.4256596565246582

In [6]:
# если бы is_fast=False:
# 0.41233325004577637

"""
-4,96875

"""
import time


data = {'prompt': 'The weather is amazing! It is so ', 'substring': 'good day! bad day, I hate it'}
s = time.time()
x = requests.post(url, json = data)
e = time.time()

print(x.text)
e - s

["good"]


0.15969228744506836

In [11]:
import requests
import time
import random
import string
from concurrent.futures import ThreadPoolExecutor

# URL to which requests will be sent

def generate_random_data():
    random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=600))
    return {"inputs": f"{random_string}?"}

# Function to send a request and return the response content
def send_request(data):
    response = requests.post(url, json=data)
    return response.content

# Number of requests to send
num_requests = 10

# Sample data for requests

substirng = "Создай задачу купить конфет, статус в процессе"

# substring_example = {'prompt': prompt, 'substring': substirng}

data = {'prompt': 'The weather is amazing! It is so ', 'substring': 'good day! bad day, I hate it'}

# Start time
ts = time.time()

# Use ThreadPoolExecutor to send requests in parallel
with ThreadPoolExecutor(max_workers=num_requests) as executor:
    # Submit all requests and collect the futures
    futures = [executor.submit(send_request, data) for _ in range(num_requests)]

# Wait for all requests to complete and retrieve the results
results = [future.result() for future in futures]

# Stop time
time_stop = time.time()
print("Time taken:", time_stop - ts)

# Print the result of each request
for idx, result in enumerate(results):
    print(f"Result of request {idx + 1}: {result.decode('utf-8')}")

Time taken: 1.1272075176239014
Result of request 1: ["good"]
Result of request 2: ["good"]
Result of request 3: ["good"]
Result of request 4: ["good"]
Result of request 5: ["good"]
Result of request 6: ["good"]
Result of request 7: ["good"]
Result of request 8: ["good"]
Result of request 9: ["good"]
Result of request 10: ["good"]


In [12]:
%%time
ts = time.time()

# Send requests synchronously
for _ in range(100):
    status_code = send_request(data)
time_stop = time.time()
print(time_stop-ts)

13.488179206848145
CPU times: user 180 ms, sys: 14.3 ms, total: 195 ms
Wall time: 13.5 s


In [65]:
candidates = [' so  ', ' so  I', ' so  I ', ' so  I h', ' so  I ha', ' so  I hat', ' so  I hate', ' so  I hate ', ' so  I hate i', ' so  I hate it', ' so  b', ' so  ba', ' so  bad', ' so  bad ', ' so  bad d', ' so  bad da', ' so  bad day', ' so  bad day,', ' so  bad day, ', ' so  bad day, I', ' so  bad day, I ', ' so  bad day, I h', ' so  bad day, I ha', ' so  bad day, I hat', ' so  bad day, I hate', ' so  d', ' so  da', ' so  day', ' so  day!', ' so  day! ', ' so  day! b', ' so  day! ba', ' so  day! bad', ' so  day! bad ', ' so  day! bad d', ' so  day! bad da', ' so  day! bad day', ' so  day! bad day,', ' so  day! bad day, ', ' so  day! bad day, I', ' so  day,', ' so  day, ', ' so  day, I', ' so  day, I ', ' so  day, I h', ' so  day, I ha', ' so  day, I hat', ' so  day, I hate', ' so  day, I hate ', ' so  day, I hate i', ' so  day, I hate it', ' so  h', ' so  ha', ' so  hat', ' so  hate', ' so  hate ', ' so  hate i', ' so  hate it', ' so  i', ' so  it', ' so !', ' so ! ', ' so ! b', ' so ! ba', ' so ! bad', ' so ! bad ', ' so ! bad d', ' so ! bad da', ' so ! bad day', ' so ! bad day,', ' so ! bad day, ', ' so ! bad day, I', ' so ! bad day, I ', ' so ! bad day, I h', ' so ! bad day, I ha', ' so ! bad day, I hat', ' so ,', ' so , ', ' so , I', ' so , I ', ' so , I h', ' so , I ha', ' so , I hat', ' so , I hate', ' so , I hate ', ' so , I hate i', ' so , I hate it', ' so I', ' so I ', ' so I h', ' so I ha', ' so I hat', ' so I hate', ' so I hate ', ' so I hate i', ' so I hate it', ' so a', ' so ad', ' so ad ', ' so ad d', ' so ad da', ' so ad day', ' so ad day,', ' so ad day, ', ' so ad day, I', ' so ad day, I ', ' so ad day, I h', ' so ad day, I ha', ' so ad day, I hat', ' so ad day, I hate', ' so ad day, I hate ', ' so ad day, I hate i', ' so at', ' so ate', ' so ate ', ' so ate i', ' so ate it', ' so ay', ' so ay!', ' so ay! ', ' so ay! b', ' so ay! ba', ' so ay! bad', ' so ay! bad ', ' so ay! bad d', ' so ay! bad da', ' so ay! bad day', ' so ay! bad day,', ' so ay! bad day, ', ' so ay! bad day, I', ' so ay! bad day, I ', ' so ay! bad day, I h', ' so ay,', ' so ay, ', ' so ay, I', ' so ay, I ', ' so ay, I h', ' so ay, I ha', ' so ay, I hat', ' so ay, I hate', ' so ay, I hate ', ' so ay, I hate i', ' so ay, I hate it', ' so b', ' so ba', ' so bad', ' so bad ', ' so bad d', ' so bad da', ' so bad day', ' so bad day,', ' so bad day, ', ' so bad day, I', ' so bad day, I ', ' so bad day, I h', ' so bad day, I ha', ' so bad day, I hat', ' so bad day, I hate', ' so bad day, I hate ', ' so d', ' so d ', ' so d d', ' so d da', ' so d day', ' so d day!', ' so d day! ', ' so d day! b', ' so d day! ba', ' so d day! bad', ' so d day! bad ', ' so d day! bad d', ' so d day! bad da', ' so d day! bad day', ' so d day! bad day,', ' so d day! bad day, ', ' so d day,', ' so d day, ', ' so d day, I', ' so d day, I ', ' so d day, I h', ' so d day, I ha', ' so d day, I hat', ' so d day, I hate', ' so d day, I hate ', ' so d day, I hate i', ' so d day, I hate it', ' so da', ' so day', ' so day!', ' so day! ', ' so day! b', ' so day! ba', ' so day! bad', ' so day! bad ', ' so day! bad d', ' so day! bad da', ' so day! bad day', ' so day! bad day,', ' so day! bad day, ', ' so day! bad day, I', ' so day! bad day, I ', ' so day,', ' so day, ', ' so day, I', ' so day, I ', ' so day, I h', ' so day, I ha', ' so day, I hat', ' so day, I hate', ' so day, I hate ', ' so day, I hate i', ' so day, I hate it', ' so e', ' so e ', ' so e i', ' so e it', ' so g', ' so go', ' so goo', ' so good', ' so good ', ' so good d', ' so good da', ' so good day', ' so good day!', ' so good day! ', ' so good day! b', ' so good day! ba', ' so good day! bad', ' so good day! bad ', ' so good day! bad d', ' so good day! bad da', ' so h', ' so ha', ' so hat', ' so hate', ' so hate ', ' so hate i', ' so hate it', ' so i', ' so it', ' so o', ' so od', ' so od ', ' so od d', ' so od da', ' so od day', ' so od day!', ' so od day! ', ' so od day! b', ' so od day! ba', ' so od day! bad', ' so od day! bad ', ' so od day! bad d', ' so od day! bad da', ' so od day! bad day', ' so od day! bad day,', ' so oo', ' so ood', ' so ood ', ' so ood d', ' so ood da', ' so ood day', ' so ood day!', ' so ood day! ', ' so ood day! b', ' so ood day! ba', ' so ood day! bad', ' so ood day! bad ', ' so ood day! bad d', ' so ood day! bad da', ' so ood day! bad day', ' so t', ' so te', ' so te ', ' so te i', ' so te it', ' so y', ' so y!', ' so y! ', ' so y! b', ' so y! ba', ' so y! bad', ' so y! bad ', ' so y! bad d', ' so y! bad da', ' so y! bad day', ' so y! bad day,', ' so y! bad day, ', ' so y! bad day, I', ' so y! bad day, I ', ' so y! bad day, I h', ' so y! bad day, I ha', ' so y,', ' so y, ', ' so y, I', ' so y, I ', ' so y, I h', ' so y, I ha', ' so y, I hat', ' so y, I hate', ' so y, I hate ', ' so y, I hate i', ' so y, I hate it']

In [102]:
candidates

[' so  ',
 ' so  I',
 ' so  I ',
 ' so  I h',
 ' so  I ha',
 ' so  I hat',
 ' so  I hate',
 ' so  I hate ',
 ' so  I hate i',
 ' so  I hate it',
 ' so  b',
 ' so  ba',
 ' so  bad',
 ' so  bad ',
 ' so  bad d',
 ' so  bad da',
 ' so  bad day',
 ' so  bad day,',
 ' so  bad day, ',
 ' so  bad day, I',
 ' so  bad day, I ',
 ' so  bad day, I h',
 ' so  bad day, I ha',
 ' so  bad day, I hat',
 ' so  bad day, I hate',
 ' so  d',
 ' so  da',
 ' so  day',
 ' so  day!',
 ' so  day! ',
 ' so  day! b',
 ' so  day! ba',
 ' so  day! bad',
 ' so  day! bad ',
 ' so  day! bad d',
 ' so  day! bad da',
 ' so  day! bad day',
 ' so  day! bad day,',
 ' so  day! bad day, ',
 ' so  day! bad day, I',
 ' so  day,',
 ' so  day, ',
 ' so  day, I',
 ' so  day, I ',
 ' so  day, I h',
 ' so  day, I ha',
 ' so  day, I hat',
 ' so  day, I hate',
 ' so  day, I hate ',
 ' so  day, I hate i',
 ' so  day, I hate it',
 ' so  h',
 ' so  ha',
 ' so  hat',
 ' so  hate',
 ' so  hate ',
 ' so  hate i',
 ' so  hate it',
 ' so  i

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

access_token = "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"
model_name = "meta-llama/Meta-Llama-3-8B"

model_kwargs = {
    'token': access_token,
    'device_map': 'auto',
    'attn_implementation': 'flash_attention_2',
    'torch_dtype': torch.bfloat16
}

tokenizer_kwargs = {
    'token': access_token,
    'device_map': 'auto'
}

model = AutoModelForCausalLM.from_pretrained(model_name, **model_kwargs)
tokenizer = AutoTokenizer.from_pretrained(model_name, **tokenizer_kwargs)

/home/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 4/4 [00:02<00:00,  1.70it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [4]:
if not tokenizer.pad_token:
    tokenizer.pad_token = tokenizer.eos_token

In [7]:
def candidate_sequence(prompt, context, max_token_length=16):
    
    # Calculate the restriction based on the length of the text and the maximum token length
    restriction = min(len(context) + 1, max_token_length)
    # Initialize an empty set to store unique substring candidates
    substring_candidates = set()

    for i in range(len(context)):
        for j in range(i+1, min(len(context)+1, i+1+restriction)):
            substring_candidates.add(context[i:j])

    # Sort the set of substring candidates for reproducibility
    substring_candidates = sorted(substring_candidates)
    # Prefix each candidate with the prompt to form complete sequences
    sequences = [prompt + candidate for candidate in substring_candidates]
        
    return sequences

In [275]:
prompt_test = 'The weather is amazing! It is so '
substring_context = 'good day! bad day, I hate it'

tokenized_prompt = tokenizer(prompt_test,
                             return_tensors="pt",
                             padding=True,
                             add_special_tokens=False)['input_ids']
last_part = tokenizer.decode(tokenized_prompt[0, -2:])
common_part = tokenizer.decode(tokenized_prompt[0, :-2])
last_part

' so '

In [193]:
options = candidate_sequence('', substring_context)
options[1:10]

[' I',
 ' I ',
 ' I h',
 ' I ha',
 ' I hat',
 ' I hate',
 ' I hate ',
 ' I hate i',
 ' I hate it']

In [194]:
options = tokenizer(options[1:10],
          return_tensors="pt",
          padding=True,
          add_special_tokens=False)['input_ids']
options

tensor([[   358, 128001, 128001],
        [   358,    220, 128001],
        [   358,    305, 128001],
        [   358,   6520, 128001],
        [   358,   9072, 128001],
        [   358,  12491, 128001],
        [   358,  12491,    220],
        [   358,  12491,    602],
        [   358,  12491,    433]])

In [195]:
options_lenghts = torch.sum(options != tokenizer.pad_token_id, dim=1)
options_lenghts

tensor([1, 2, 2, 2, 2, 2, 3, 3, 3])

In [196]:
length_option_map = {}
for i, option in enumerate(options):
    length_option_map.setdefault(options_lenghts[i].item(), []).append(option[:options_lenghts[i]].tolist())

length_option_map

{1: [[358]],
 2: [[358, 220], [358, 305], [358, 6520], [358, 9072], [358, 12491]],
 3: [[358, 12491, 220], [358, 12491, 602], [358, 12491, 433]]}

In [197]:
len2_decoded = tokenizer.batch_decode(length_option_map[2])
len2_decoded

[' I ', ' I h', ' I ha', ' I hat', ' I hate']

In [198]:
length_option_map[2]

[[358, 220], [358, 305], [358, 6520], [358, 9072], [358, 12491]]

In [103]:
import pygtrie

len2_decoded = ['5 ', ' I ', ' I ha', ' I hat', ' I hate']

t = pygtrie.CharTrie()
for w in len2_decoded:
    t[w] = True

for w in len2_decoded:
    print(f"{w}: {t.has_subtrie(w)}")

5 : False
 I : True
 I ha: True
 I hat: True
 I hate: False


In [108]:
options = candidate_sequence('', substring_context)
print(len(options))
options = tokenizer(options,
          return_tensors="pt",
          padding=True,
          add_special_tokens=False)['input_ids']
options

304


tensor([[   220, 128001, 128001,  ..., 128001, 128001, 128001],
        [   358, 128001, 128001,  ..., 128001, 128001, 128001],
        [   358,    220, 128001,  ..., 128001, 128001, 128001],
        ...,
        [    88,     11,    358,  ...,    220, 128001, 128001],
        [    88,     11,    358,  ...,    602, 128001, 128001],
        [    88,     11,    358,  ...,    433, 128001, 128001]])

In [109]:
options_lenghts = torch.sum(options != tokenizer.pad_token_id, dim=1)
options_lenghts

tensor([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 1, 1, 1, 2, 2, 2, 2, 3, 4, 4, 5, 5, 5, 5,
        5, 1, 1, 1, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 6, 6, 2, 3, 3, 4, 4, 4, 4, 4,
        5, 5, 5, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 5, 5,
        6, 6, 6, 6, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 1, 2, 2, 2, 2, 2, 3, 3, 3,
        1, 1, 2, 2, 2, 2, 3, 4, 4, 5, 5, 5, 5, 5, 6, 6, 1, 1, 2, 2, 2, 1, 2, 3,
        3, 3, 3, 4, 4, 4, 4, 5, 6, 6, 7, 7, 2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 1,
        1, 1, 2, 2, 2, 2, 3, 4, 4, 5, 5, 5, 5, 5, 6, 1, 2, 2, 2, 2, 3, 4, 4, 4,
        4, 5, 5, 5, 5, 6, 7, 3, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 1, 1, 2, 3, 3, 3,
        3, 4, 4, 4, 4, 5, 6, 6, 7, 2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 1, 2, 2, 2,
        1, 1, 1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 4, 5, 5, 5, 1, 1, 1, 2, 3, 3, 3, 1,
        1, 1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 1, 1, 2, 2, 2, 2, 3,
        4, 4, 4, 4, 5, 5, 5, 5, 1, 1, 2, 2, 2, 1, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5,
        6, 6, 7, 7, 7, 2, 3, 3, 4, 4, 4,

In [110]:
length_option_map = {}
for i, option in enumerate(options):
    length_option_map.setdefault(options_lenghts[i].item(), []).append(option[:options_lenghts[i]].tolist())

length_option_map

{1: [[220],
  [358],
  [293],
  [13081],
  [3958],
  [294],
  [3067],
  [1938],
  [305],
  [6520],
  [9072],
  [12491],
  [602],
  [433],
  [0],
  [11],
  [40],
  [64],
  [329],
  [266],
  [349],
  [352],
  [65],
  [4749],
  [14176],
  [67],
  [3315],
  [1316],
  [68],
  [70],
  [3427],
  [63148],
  [19045],
  [71],
  [4317],
  [9379],
  [72],
  [275],
  [78],
  [347],
  [2689],
  [1411],
  [83],
  [668],
  [88]],
 2: [[358, 220],
  [358, 305],
  [358, 6520],
  [358, 9072],
  [358, 12491],
  [3958, 220],
  [3958, 294],
  [3958, 3067],
  [3958, 1938],
  [1938, 0],
  [1938, 11],
  [12491, 220],
  [12491, 602],
  [12491, 433],
  [0, 220],
  [0, 293],
  [0, 13081],
  [0, 3958],
  [11, 220],
  [11, 358],
  [40, 220],
  [40, 305],
  [40, 6520],
  [40, 9072],
  [40, 12491],
  [329, 220],
  [329, 294],
  [329, 3067],
  [329, 1938],
  [349, 220],
  [349, 602],
  [349, 433],
  [352, 0],
  [352, 11],
  [14176, 220],
  [14176, 294],
  [14176, 3067],
  [14176, 1938],
  [67, 220],
  [67, 294],
  [67

In [111]:
len_filtered_map = {}
filtered = []

for length in length_option_map:
    decoded_options = tokenizer.batch_decode(length_option_map[length])
    t = pygtrie.CharTrie()
    for option in decoded_options:
        t[option] = True

    for option in decoded_options:
        if not t.has_subtrie(option):
            len_filtered_map.setdefault(length, []).append(option)
    
len_filtered_map

for length in len_filtered_map:
    tokenized_options = tokenizer(len_filtered_map[length],
                         return_tensors="pt",
                         padding=True,
                         add_special_tokens=False)['input_ids']

    if length == 1:
        reversed_options = [w[::-1] for w in tokenizer.batch_decode(tokenized_options)]
    else:
        reversed_options = [w[::-1] for w in tokenizer.batch_decode(tokenized_options[:, :-1])]

    t = pygtrie.CharTrie()
    for option in reversed_options:
        t[option] = True

    added = set()

    for i, option in enumerate(reversed_options):
        if not t.has_subtrie(option) and option not in added:
            
            filtered.append(len_filtered_map[length][i])
            print(f"'{len_filtered_map[length][i]}'")
    
len(filtered)

' I'
' bad'
' day'
' hate'
' it'
'!'
','
'good'
'hat'
' I hate'
' bad day'
' day!'
' day,'
' hate it'
'! bad'
', I'
'good day'
'hate'
' I hate it'
' bad day,'
' day! bad'
' day, I'
'! bad day'
', I hate'
'good day!'
' bad day, I'
' day! bad day'
' day, I hate'
'! bad day,'
', I hate it'
'good day! bad'
' bad day, I hate'
' day! bad day,'
' day, I hate it'
'! bad day, I'
'good day! bad da'
' day! bad day, I'
'! bad day, I hat'
'bad day, I hate '
'od day! bad day,'
'd day! bad day, '
'day! bad day, I '


42

In [276]:
restriction = 16
substring_context = substring_context.split(' ')
word_lengths = [len(word) for word in substring_context]
avg_length = (sum(word_lengths) + len(word_lengths))/len(word_lengths)
step_size = int(restriction // avg_length) + 1

substirng_candidates = set()

# Iterate over the text to generate all possible substrings within the restriction
for i in range(len(substring_context)):
    for j in range(i+1, min(len(substring_context) + 1, i + 1 + step_size)):
        candidate = " ".join(substring_context[i:j])
        substirng_candidates.add(candidate)

substirng_candidates, len(list(substirng_candidates))

({'I',
  'I hate',
  'I hate it',
  'bad',
  'bad day,',
  'bad day, I',
  'bad day, I hate',
  'day!',
  'day! bad',
  'day! bad day,',
  'day! bad day, I',
  'day,',
  'day, I',
  'day, I hate',
  'day, I hate it',
  'good',
  'good day!',
  'good day! bad',
  'good day! bad day,',
  'hate',
  'hate it',
  'it'},
 22)

In [199]:
test_options1 = ['od day! bad day,',
                'd day! bad day, ']

test_options2 = ['good',
                'od',
                'ood']

test_options3 = [' day!',
                ' day,']

test_options = tokenizer(test_options2,
                         return_tensors="pt",
                         padding=True,
                         add_special_tokens=False)['input_ids']

test_options

tensor([[19045],
        [  347],
        [ 1411]])

In [201]:
decoded_test = [w[::-1] for w in tokenizer.batch_decode(test_options)]
print(decoded_test)
t = pygtrie.CharTrie()
for option in decoded_test:
    t[option] = True

for option in decoded_test:
    if not t.has_subtrie(option):
        print(f"'{option[::-1]}'")

['doog', 'do', 'doo']
'good'


In [184]:
prompt = '''There is a request from the user to create a task in task management system. Please, extract the status of this task that will be placed in Task Management System.
Example 1: Обнови статус задачи по проведению пентеста на выполнено.
Answer: "выполнено"

Example 2: "Создай Ване задачу по рефакторингу кода. И поставь статус - в процессе"
Answer: "в процессе"

Example 3: "Покажи мне исполнителей задачи по построению графиков"
Answer: "null"

Example 4: "Создай задачу купить конфет, статус в процессе"
Answer: "'''


substring_context = "Создай задачу купить конфет, статус в процессе"


options = candidate_sequence('', substring_context)
print(len(options))
options = tokenizer(options,
          return_tensors="pt",
          padding=True,
          add_special_tokens=False)['input_ids']
options

590


tensor([[   220, 128001, 128001,  ..., 128001, 128001, 128001],
        [  5927, 128001, 128001,  ..., 128001, 128001, 128001],
        [  5927,    220, 128001,  ..., 128001, 128001, 128001],
        ...,
        [  4929, 113923,   8341,  ..., 104931, 128001, 128001],
        [  4929, 113923,   8341,  ...,  18868, 103457, 128001],
        [  4929, 113923,   8341,  ..., 121280, 128001, 128001]])

In [185]:
options_lenghts = torch.sum(options != tokenizer.pad_token_id, dim=1)
options_lenghts

tensor([1, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2, 1, 1, 1, 1, 2, 3, 4, 4, 4, 4, 5, 5, 5,
        6, 6, 1, 1, 1, 1, 2, 2, 3, 4, 4, 4, 4, 4, 5, 4, 5, 1, 1, 2, 2, 2, 3, 3,
        3, 3, 3, 4, 4, 5, 6, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 3,
        3, 3, 3, 3, 4, 3, 1, 2, 2, 2, 2, 2, 3, 2, 3, 3, 4, 4, 4, 4, 4, 5, 1, 2,
        2, 2, 3, 3, 4, 4, 4, 4, 4, 5, 6, 7, 7, 7, 1, 1, 1, 2, 3, 4, 4, 4, 4, 5,
        5, 5, 6, 6, 6, 6, 1, 2, 2, 2, 2, 2, 3, 4, 5, 5, 5, 5, 6, 6, 6, 1, 1, 2,
        3, 3, 4, 4, 4, 4, 4, 5, 4, 4, 4, 1, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5,
        5, 6, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2, 1, 1, 2, 3, 3, 3, 3, 3, 4, 5, 6, 6,
        6, 6, 7, 7, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 1, 1, 1, 2, 1, 2,
        3, 3, 3, 3, 3, 4, 3, 4, 4, 5, 5, 5, 5, 1, 1, 2, 2, 3, 4, 5, 5, 5, 5, 6,
        6, 6, 7, 7, 7, 1, 2, 2, 3, 3, 3, 3, 3, 4, 5, 6, 6, 6, 6, 7, 1, 1, 1, 2,
        2, 2, 2, 2, 3, 3, 4, 5, 5, 5, 5, 5, 1, 2, 2, 2, 2, 2, 3, 4, 5, 5, 5, 5,
        6, 6, 6, 7, 1, 1, 1, 2, 3, 3, 4,

In [186]:
length_option_map = {}
for i, option in enumerate(options):
    length_option_map.setdefault(options_lenghts[i].item(), []).append(option[:options_lenghts[i]].tolist())

length_option_map

{1: [[220],
  [5927],
  [11122],
  [44946],
  [53280],
  [109108],
  [7820],
  [88515],
  [38098],
  [113923],
  [106309],
  [107185],
  [5173],
  [12561],
  [41291],
  [101618],
  [102429],
  [110793],
  [122556],
  [5524],
  [18868],
  [111822],
  [104931],
  [121280],
  [11],
  [19871],
  [1506],
  [23680],
  [103251],
  [19039],
  [8131],
  [103457],
  [50223],
  [5591],
  [7094],
  [40590],
  [1532],
  [23297],
  [94520],
  [8341],
  [9136],
  [100484],
  [107179],
  [1840],
  [9542],
  [18264],
  [12415],
  [4898],
  [48199],
  [100737],
  [36352],
  [109667],
  [2156],
  [1482],
  [20219],
  [35387],
  [17766],
  [8164],
  [103289],
  [125093],
  [2233],
  [100442],
  [2297],
  [102121],
  [6735],
  [102879],
  [1830],
  [44613],
  [89348],
  [29893],
  [3865],
  [49907],
  [44155],
  [19916],
  [10589],
  [102055],
  [127459],
  [6148],
  [107731],
  [4929]],
 2: [[5927, 220],
  [5927, 5173],
  [5927, 12561],
  [5927, 41291],
  [5927, 101618],
  [5927, 102429],
  [5927, 110793]

In [187]:
len_filtered_map = {}
filtered = []

for length in length_option_map:
    decoded_options = tokenizer.batch_decode(length_option_map[length])
    t = pygtrie.CharTrie()
    for option in decoded_options:
        t[option] = True

    for option in decoded_options:
        if not t.has_subtrie(option):
            len_filtered_map.setdefault(length, []).append(option)
    
len_filtered_map

for length in len_filtered_map:
    tokenized_options = tokenizer(len_filtered_map[length],
                         return_tensors="pt",
                         padding=True,
                         add_special_tokens=False)['input_ids']

    if length == 1:
        reversed_options = [w[::-1] for w in tokenizer.batch_decode(tokenized_options)]
    else:
        reversed_options = [w[::-1] for w in tokenizer.batch_decode(tokenized_options[:, :-1])]

    t = pygtrie.CharTrie()
    for option in reversed_options:
        t[option] = True

    added = set()

    for i, option in enumerate(reversed_options):
        if not t.has_subtrie(option) and option not in added:
            
            filtered.append(len_filtered_map[length][i])
            print(f"'{len_filtered_map[length][i]}'")
    
len(filtered)

' в'
' зада'
' конф'
' куп'
' процессе'
' статус'
','
'С'
'ай'
'ату'
'ач'
'есс'
'ет'
'за'
'ить'
'кон'
'озд'
'пи'
'пр'
'ро'
'ста'
'цес'
'чу'
' в процессе'
' задач'
' конфет'
' купить'
' проце'
' статус в'
', статус'
'Созд'
'ай зада'
'атус'
'ачу'
'дачу'
'ессе'
'ет,'
'зада'
'ить конф'
'конф'
'оздай'
'роцес'
'стату'
'чу куп'
' в проце'
' задачу'
' конфет,'
' купить конф'
' статус в процес'
', статус в'
'Создай'
'ай задач'
'дачу куп'
'ет, статус'
'ить конфет'
'оздай зада'
'процес'
'статус'
'цессе'
'чу купить'
' задачу куп'
' конфет, статус'
' купить конфет'
' статус в проце'
', статус в проц'
'Создай зада'
'ай задачу'
'дачу купить'
'ет, статус в'
'ить конфет,'
'оздай задач'
'роцессе'
'чу купить конф'
' задачу купить'
' конфет, статус '
' купить конфет,'
', статус в проце'
'Создай задач'
'ай задачу куп'
'дачу купить конф'
'ет, статус в про'
'ить конфет, стат'
'оздай задачу'
'процессе'
'чу купить конфет'
' задачу купить к'
' купить конфет, '
'Создай задачу'
'ай задачу купить'
'ачу купить конф

100

In [188]:
tokenized_prompt = tokenizer(prompt,
                             return_tensors="pt",
                             padding=True,
                             add_special_tokens=False)['input_ids']
last_part = tokenizer.decode(tokenized_prompt[0, -2:])
common_part = tokenizer.decode(tokenized_prompt[0, :-2])
last_part

': "'

In [189]:
options = candidate_sequence('', substring_context)


In [190]:
print(sum([len(len_filtered_map[k]) for k in len_filtered_map]))
len_filtered_map

225


{1: [' в',
  ' зада',
  ' конф',
  ' куп',
  ' процессе',
  ' статус',
  ',',
  'С',
  'ада',
  'ай',
  'ату',
  'ач',
  'в',
  'да',
  'есс',
  'ет',
  'за',
  'зд',
  'ить',
  'й',
  'кон',
  'куп',
  'н',
  'озд',
  'он',
  'пи',
  'пр',
  'ро',
  'се',
  'ста',
  'та',
  'ту',
  'ть',
  'уп',
  'ус',
  'ф',
  'цес',
  'чу',
  'ь'],
 2: [' в процессе',
  ' задач',
  ' конфет',
  ' купить',
  ' проце',
  ' статус в',
  ', статус',
  'Созд',
  'адач',
  'ай зада',
  'атус',
  'ачу',
  'в процессе',
  'дай',
  'дачу',
  'ессе',
  'ет,',
  'зада',
  'здай',
  'ить конф',
  'й зада',
  'конф',
  'купить',
  'нф',
  'оздай',
  'онф',
  'оцес',
  'пить',
  'про',
  'роцес',
  'с в',
  'ссе',
  'стату',
  'т,',
  'тату',
  'тус',
  'ть конф',
  'у куп',
  'упить',
  'ус в',
  'фет',
  'цесс',
  'чу куп',
  'ь конф'],
 3: [' в проце',
  ' задачу',
  ' конфет,',
  ' купить конф',
  ' статус в процес',
  ', статус в',
  'Создай',
  'адачу',
  'ай задач',
  'атус в',
  'ачу куп',
  'в проце',
 

In [128]:
restriction = 16
substring_context = substring_context.split(' ')
word_lengths = [len(word) for word in substring_context]
avg_length = (sum(word_lengths) + len(word_lengths))/len(word_lengths)
step_size = int(restriction // avg_length) + 1

substirng_candidates = set()

# Iterate over the text to generate all possible substrings within the restriction
for i in range(len(substring_context)):
    for j in range(i+1, min(len(substring_context) + 1, i + 1 + step_size)):
        candidate = " ".join(substring_context[i:j])
        substirng_candidates.add(candidate)

substirng_candidates

{'Создай',
 'Создай задачу',
 'Создай задачу купить',
 'в',
 'в процессе',
 'задачу',
 'задачу купить',
 'задачу купить конфет,',
 'конфет,',
 'конфет, статус',
 'конфет, статус в',
 'купить',
 'купить конфет,',
 'купить конфет, статус',
 'процессе',
 'статус',
 'статус в',
 'статус в процессе'}